### ISSUE TITLE
Missing device validation in ConvertSmiHandlerUsbContext()

### ISSUE THREAD

**Issue by kuqin12** [microsoft/mu_feature_mm_supv#14]
ConvertSmiHandlerUsbContext() is called by SmiHandlerProfileRegisterHandler() which is called by ProcessUserHandlerReg() when the supervisor dispatcher handles a SMM_MM_HDL_REG_1/SMM_MM_HDL_REG_2 request to register a child SMI handler with a gEfiSmmUsbDispatch2ProtocolGuid handler guid. ConvertSmiHandlerUsbContext() is handed a user space provided context and context size, and it will convert an EFI_SMM_USB_REGISTER_CONTEXT structure to a SMI_HANDLER_PROFILE_USB_REGISTER_CONTEXT structure. An EFI_SMM_USB_REGISTER_CONTEXT structure contains a device pointer and a type. ConvertSmiHandlerUsbContext() will call GetDevicePathSize() to get the device path size and then allocate a SMI_HANDLER_PROFILE_USB_REGISTER_CONTEXT with enough room for the device and copy it over into the structure. 

The problem here is that UsbContext->Device is a user-space provided pointer to a variable-length structure that more or less acts as a sort of linked list (but instead of next pointers, it has 16-bit length fields) of device elements, where each element has a type, subtype a length and content. GetDevicePathSize() has no idea it runs inside the supervisor and has no concept of user-space provided pointers. This is a problem. It doesn't call InspectTargetRangeOwnership(); furthermore, even if it did, the length could change after the call to InspectTargetRangeOwnership() because the pointer comes from user-space (who might be able to change the data asynchronously, either through a 2nd core or by utilizing async DMA or async IO) or even the device pointer could change. Additionally, there is no check to make sure the UsbContext size is the size of an EFI_SMM_USB_REGISTER_CONTEXT structure; there is just an assert.

Fix Recommendation:
- on entry of the function, make sure UsbContextSize is at least sizeof (EFI_SMM_USB_REGISTER_CONTEXT)
- capture the device pointer
- InspectTargetRangeOwnership on the captured device pointer, with a size of sizeof(EFI_DEVICE_PATH_PROTOCOL)
- have to implement your own GetDevicePathSize()

Acknowledgement:
Thanks to @iljavs for reporting this issue.

**Comment by kuqin12** [comment]
The impact of handler profile related bugs is trivial because MMI handler profile is a test/development feature, which should not be enabled in the release firmware.

**Comment by makubacki** [comment]
@kuqin12, should we close this issue now?
